open5gs:
  image:
    repository: umakantk/open5gs
    pullPolicy: Always
    tag: "benchmark"
  upf:
    hostNetwork: false
    tunintf: "ogstun"
  pfcp:
    port: 8805
  gtpv1:
    port: 2152
  gtpv2:
    port: 2153
  ran:
    port: 30412

ztx:
  enabled: true
  authentication: true
  encryption: true
  tcp: true
  udp: true
  sctp: true
  name: "ztx"
  image:
    repository: umakantk/ztx
    pullPolicy: Always
    tag: "v1"
    initTag: "init"
    controllerTag: "v2"
  health:
    port: 8080

monitoring:
  prometheus:
    enabled: true
    nodeport: 30090

pool:
  key: 128
  val: 65536

max:
  ue: 2048

ueransim:
  image:
    repository: umakantk/ueransim
    pullPolicy: Always
    tag: "ztx_01"

dnn: internet

amf:
  mcc: 208
  mnc: 93
  tac: 1

# Primary/Native kubernetes interface
k8s:
  podInterface: eth0

webui:
  image:
    repository: registry.gitlab.com/infinitydon/registry/open5gs-webui
    pullPolicy: Always
    tag: "v2.2.2"
  ingress:
    enabled: false
    hosts:
      - name: open5gs-epc.local
        paths: ["/"]
        tls: false

pcs:
  nodeAffinity:
    enabled: true
    amf: amf
    smf: smf
    upf: upf
    ausf: amf
    bsf: amf
    pcf: amf
    mongo: upf
    nrf: upf
    nssf: upf
    scp: smf
    udr: smf
    udm: smf
    test: master
    webui: master
    ztx: master
  enableMongoReplicaSet: false
  dbCommEnabled:
    amf: false
    smf: false
    upf: false
  upsertApiEnabled:
    amf:
      create: false
    smf:
      create: false
    upf:
      create: false
  updateApiEnabled:
    amf:
      n1n2: true
      modify: true
    smf:
      n1n2: true
      modify: true
    upf:
      modify: true
  replaceApiEnabled:
    amf:
      n1n2: false
      modify: false
    smf:
      n1n2: false
      modify: false
    upf:
      modify: false
  blockingApiEnabled:
    amf:
      create: true
      n1n2: true
      modifyreq: true
      modifyrsp: true
    upf:
      create: true
      modifyrsp: true

  isProceduralStateless:
    amf: false
    smf: false
    upf: false
  dbCollectioname:
    amf: "amf"
    smf: "smf"
    upf: "upf"
  enableSingleRead:
    amf: false
    smf: false
    upf: false

mongodb:
  username: root
  password: root
  image:
    repository: umakantk/open5gs-mongo
    pullPolicy: IfNotPresent
    tag: "ztx_02"
