FROM ubuntu:22.04

ENV DEBIAN_FRONTEND noninteractive
ARG ARG_TIMEZONE=America/Indiana/Indianapolis
ENV ENV_TIMEZONE ${ARG_TIMEZONE}

RUN apt -y update

RUN apt-get update && apt-get -yq dist-upgrade && apt-get --no-install-recommends -qqy install wget git vim nano make g++ libsctp-dev lksctp-tools net-tools iproute2 libssl-dev tcpdump curl jq iputils-ping gdb python3-pip tzdata openssh-client cmake

ENV TZ="America/Indiana/Indianapolis"

RUN pip3 install pymongo

RUN cmake --version

ENV PCS_SETUP_TUN_INTF=false

RUN cd && git clone -b ztx_01 https://github.com/UmakantKulkarni/UERANSIM && cd UERANSIM && make

WORKDIR /root/

RUN git clone -b benchmark https://github.com/UmakantKulkarni/scripts && cd scripts && chmod +x *

RUN cp UERANSIM/build/nr-* /usr/local/bin/

# sync timezone
RUN echo '$ENV_TIMEZONE' > /etc/timezone \
    && ln -fsn /usr/share/zoneinfo/$ENV_TIMEZONE /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata

CMD ["sh", "-c", "sleep infinity"]
