FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ARG ARG_TIMEZONE=America/Indiana/Indianapolis
ENV ENV_TIMEZONE=${ARG_TIMEZONE}

RUN apt -y update

RUN apt-get update && apt-get -yq dist-upgrade && apt-get --no-install-recommends -qqy install wget git vim nano make g++ libsctp-dev lksctp-tools net-tools iproute2 libssl-dev tcpdump curl jq iputils-ping gdb python3-pip tzdata openssh-client cmake gnupg

ENV TZ="America/Indiana/Indianapolis"

RUN pip3 install pymongo

RUN cmake --version

ENV PCS_SETUP_TUN_INTF=false

RUN cd && git clone -b ztx_01 https://github.com/UmakantKulkarni/UERANSIM && cd UERANSIM && make

# Define the Go version to install
ENV GO_VERSION=1.23.4
RUN cd && wget https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz && rm go${GO_VERSION}.linux-amd64.tar.gz
ENV PATH="/usr/local/go/bin:$PATH"
RUN go version
RUN cd && git clone https://github.com/UmakantKulkarni/gnbsim && cd gnbsim && go build
RUN cd

WORKDIR /root/

RUN git clone -b ztx_cl https://github.com/UmakantKulkarni/scripts && cd scripts && chmod +x *

RUN cp UERANSIM/build/nr-* /usr/local/bin/

# sync timezone
RUN echo '$ENV_TIMEZONE' > /etc/timezone \
    && ln -fsn /usr/share/zoneinfo/$ENV_TIMEZONE /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata

RUN wget -qO /usr/share/keyrings/mongodb-server-8.0.gpg https://www.mongodb.org/static/pgp/server-8.0.asc && \
    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/8.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-8.0.list && \
    apt-get update && \
    apt-get install -y mongodb-mongosh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mongosh --version

CMD ["sh", "-c", "sleep infinity"]
