apiVersion: v1
kind: Service
metadata:
  name: open5gs-ausf
  labels:
    epc-mode: ausf
spec:
  selector:
    epc-mode: ausf
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-ausf-metrics
  labels:
    epc-mode: ausf
spec:
  selector:
    epc-mode: ausf
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-ausf-deployment
  labels:
    epc-mode: ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: ausf
  template:
    metadata:
      labels:
        epc-mode: ausf
    spec:
      {{ if .Values.pcs.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pcs-nf-type
                operator: In
                values:
                - {{ .Values.pcs.nodeAffinity.ausf | quote }}
      {{ end }}
      {{- include "ztxInitContainer" . | nindent 6 }}
      serviceAccountName: open5gs
      containers:
        {{- include "ztxAppTemplate" . | nindent 8 }}
        - name: ausf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-ausfd", "-c", "/open5gs/config-map/ausf.yaml"]
          env:
          - name: DB_URI
            value: {{ template "mongodbUri" . | quote }}
          volumeMounts:
          - name: open5gs-ausf-config
            mountPath: /open5gs/config-map/ausf.yaml
            subPath: "ausf.yaml"
      volumes:
        - name: open5gs-ausf-config
          configMap:
            name: open5gs-ausf-config