apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-bsf-config
  labels:
    epc-mode: bsf
data:
  bsf.yaml: |
    logger:
      file: /var/log/open5gs/bsf.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 2048  # The number of UE can be increased depending on memory size.
    #    peer: 64

    bsf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
            advertise: open5gs-bsf
            no_tls: true
        client:
          no_tls: true
    #      nrf:
    #        - uri: http://open5gs-nrf:80
          scp:
            - uri: http://open5gs-scp:80