apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
spec:
  selector:
    matchLabels:
      app: microservice
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice
    spec:
      {{ if .Values.pcs.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pcs-nf-type
                operator: In
                values:
                - {{ .Values.pcs.nodeAffinity.microservice | quote }}
      {{ end }}
      hostNetwork: {{ .Values.attack.hostNetwork }}
      serviceAccountName: open5gs
      containers:
        - name: microservice
          image: "{{ .Values.attack.image.repository }}:{{ .Values.attack.image.tag }}"
          imagePullPolicy: {{ .Values.attack.image.pullPolicy }}
          command: [ "python3", "/root/5GUnSec/ciliumAttack.py", "cilium_wg0" , "{{ .Values.attack.enabled }}"]
          env:
            - name: DB_URI
              {{ if .Values.pcs.enableMongoReplicaSet }}
              value: "mongodb://mongodb-svc/"
              {{ else }}
              value: "mongodb://mongodb-svc/"
              {{ end }}
