{{- define "wait-for-paas" -}}
{{ include "mongodb-wait" . }}
{{- if .Values.monitoring.prometheus.enabled -}}
{{ include "prometheus-wait" . }}
{{- end }}
{{- end -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-test-deployment
spec:
  selector:
    matchLabels:
      app: open5gs-test
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs-test
    spec:
      {{ if .Values.pcs.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pcs-nf-type
                operator: In
                values:
                - {{ .Values.pcs.nodeAffinity.test | quote }}
      {{ end }}
      {{- include "ztxInitContainer" . | nindent 6 }}
      serviceAccountName: open5gs
      containers:
        {{- include "ztxAppTemplate" . | nindent 8 }}
        - name: test
          image: "{{ .Values.ueransim.image.repository }}:{{ .Values.ueransim.image.tag }}"
          imagePullPolicy: {{ .Values.ueransim.image.pullPolicy }}
          securityContext:
            privileged: true
          command: [ "bash", "-c" ]
          args:
            - {{ include "wait-for-paas" . | indent 14 }}
            - sleep infinity
          env:
            - name: DB_URI
              {{ if .Values.pcs.enableMongoReplicaSet }}
              value: "mongodb://mongodb-svc/"
              {{ else }}
              value: "mongodb://mongodb-svc/"
              {{ end }}
