apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-test-deployment
spec:
  selector:
    matchLabels:
      app: open5gs-test
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs-test
    spec:
      {{ if .Values.pcs.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pcs-nf-type
                operator: In
                values:
                - {{ .Values.pcs.nodeAffinity.test | quote }}
      {{ end }}
      {{- include "ztxInitContainer" . | nindent 6 }}
      serviceAccountName: open5gs
      containers:
        {{- include "ztxAppTemplate" . | nindent 8 }}
        - name: test
          image: "{{ .Values.ueransim.image.repository }}:{{ .Values.ueransim.image.tag }}"
          imagePullPolicy: {{ .Values.ueransim.image.pullPolicy }}
          securityContext:
            privileged: true
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "sleep infinity"]
          env:
            - name: DB_URI
              {{ if .Values.pcs.enableMongoReplicaSet }}
              value: "mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@mongodb-svc/"
              {{ else }}
              value: "mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@mongodb-svc/"
              {{ end }}
