apiVersion: v1
kind: ServiceAccount
metadata:
  name: open5gs
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: service-and-endpoint-reader
rules:
- apiGroups: [""]
  resources: ["endpoints", "services", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-and-endpoint-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: open5gs
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: service-and-endpoint-reader
  apiGroup: rbac.authorization.k8s.io
