apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-scp-config
  labels:
    epc-mode: scp
data:
  scp.yaml: |
    logger:
      file:
        path: /var/log/open5gs/scp.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 2048  # The number of UE can be increased depending on memory size.
    #    peer: 64

    scp:
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
            advertise: open5gs-scp
        client:
          nrf:
            - uri: http://open5gs-nrf:80
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090