apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udr-config
  labels:
    epc-mode: udr
data:
  udr.yaml: |
    db_uri: {{ .Values.mongodb.sauri | quote }}
    logger:
      file: /var/log/open5gs/udr.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 2048  # The number of UE can be increased depending on memory size.
    #    peer: 64

    udr:
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
            advertise: open5gs-udr
            no_tls: true
        client:
          no_tls: true
    #      nrf:
    #        - uri: http://open5gs-nrf:80
          scp:
            - uri: http://open5gs-scp:80
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090